<a href="https://colab.research.google.com/github/Aachal-Sharma/Housing-Price-Prediction-using-Multi-Linear-Regression/blob/main/multi_linear_regression_for_house_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("yasserh/housing-prices-dataset")
data_path = path + '/Housing.csv'  # Replace with the correct path and filename
df = pd.read_csv(data_path)

In [ ]:
df

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [ ]:

df['mainroad'] = df['mainroad'].map({'yes':1,'no':0})
df['guestroom'] = df['guestroom'].map({'yes': 1, 'no': 0})
df['basement']=df['basement'].map({'yes':1,'no':0})
df['hotwaterheating']=df['hotwaterheating'].map({'yes':1,'no':0})
df['airconditioning']=df['airconditioning'].map({'yes':1,'no':0})
df['prefarea']=df['prefarea'].map({'yes':1,'no':0})
df['furnishingstatus']=df['furnishingstatus'].map({'furnished':1,'semi-furnished':2,'unfurnished':3})

In [ ]:
x=df.iloc[:,1:]

In [ ]:
x

area  bedrooms  bathrooms  stories  mainroad  guestroom  basement  \
0    7420         4          2        3         1          0         0   
1    8960         4          4        4         1          0         0   
2    9960         3          2        2         1          0         1   
3    7500         4          2        2         1          0         1   
4    7420         4          1        2         1          1         1   
..    ...       ...        ...      ...       ...        ...       ...   
540  3000         2          1        1         1          0         1   
541  2400         3          1        1         0          0         0   
542  3620         2          1        1         1          0         0   
543  2910         3          1        1         0          0         0   
544  3850         3          1        2         1          0         0   

     hotwaterheating  airconditioning  parking  prefarea  furnishingstatus  
0                  0                1        2         1                 1  
1                  0                1        3         0                 1  
2                  0                0        2         1                 2  
3                  0                1        3         1                 1  
4                  0                1        2         0                 1  
..               ...              ...      ...       ...               ...  
540                0                0        2         0                 3  
541                0                0        0         0                 2  
542                0                0        0         0                 3  
543                0                0        0         0                 1  
544                0                0        0         0                 3  

[545 rows x 12 columns]

In [ ]:
y=df.iloc[:,0]

In [ ]:
y

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...   
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
x_train

area  bedrooms  bathrooms  stories  mainroad  guestroom  basement  \
542   3620         2          1        1         1          0         0   
496   4000         2          1        1         1          0         0   
484   3040         2          1        1         0          0         0   
507   3600         2          1        1         1          0         0   
252   9860         3          1        1         1          0         0   
..     ...       ...        ...      ...       ...        ...       ...   
70    4000         3          2        2         1          0         1   
277  10360         2          1        1         1          0         0   
9     5750         3          2        4         1          1         0   
359   3600         3          1        1         1          0         0   
192   6600         3          1        1         1          1         1   

     hotwaterheating  airconditioning  parking  prefarea  furnishingstatus  
542                0                0        0         0                 3  
496                0                0        0         0                 3  
484                0                0        0         0                 3  
507                0                0        0         0                 3  
252                0                0        0         0                 2  
..               ...              ...      ...       ...               ...  
70                 0                1        0         1                 2  
277                0                0        1         1                 2  
9                  0                1        1         1                 3  
359                0                0        1         0                 3  
192                0                0        0         1                 1  

[436 rows x 12 columns]

In [ ]:
x_test

area  bedrooms  bathrooms  stories  mainroad  guestroom  basement  \
239   4000         3          1        2         1          0         0   
113   9620         3          1        1         1          0         1   
325   3460         4          1        2         1          0         0   
66   13200         2          1        1         1          0         1   
479   3660         4          1        2         0          0         0   
..     ...       ...        ...      ...       ...        ...       ...   
76    6420         3          2        3         1          0         0   
132   5200         3          1        3         1          0         0   
311   6060         2          1        1         1          0         1   
464   4500         2          1        2         1          0         0   
155   6100         3          2        1         1          0         1   

     hotwaterheating  airconditioning  parking  prefarea  furnishingstatus  
239                0                0        1         0                 1  
113                0                0        2         1                 1  
325                0                1        0         0                 2  
66                 1                0        1         0                 1  
479                0                0        0         0                 3  
..               ...              ...      ...       ...               ...  
76                 0                1        0         1                 1  
132                0                1        0         0                 2  
311                0                0        1         0                 2  
464                1                0        1         0                 2  
155                0                0        2         1                 1  

[109 rows x 12 columns]

In [ ]:
y_train

542    1750000
496    2695000
484    2870000
507    2590000
252    4515000
        ...   
70     6790000
277    4305000
9      9800000
359    3710000
192    5040000
Name: price, Length: 436, dtype: int64

In [ ]:
y_test

239    4585000
113    6083000
325    4007500
66     6930000
479    2940000
        ...   
76     6650000
132    5810000
311    4123000
464    3080000
155    5530000
Name: price, Length: 109, dtype: int64

In [ ]:
from os import register_at_fork
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(x_train,y_train)

LinearRegression()

In [ ]:
from sklearn.metrics import r2_score
y_pred=LR.predict(x_test)
r2_score(y_test,y_pred)

0.6578047592637595

In [ ]:
y_pred

array([ 4019080.69890147,  6258021.768564  ,  4392719.13411047,
        7335082.21688194,  2892857.56615675,  7084655.57701774,
        3258634.73504731,  3196499.16068631,  3520106.01134941,
        8359610.28845465,  6646926.36096856,  3788844.63269237,
        3734072.96467981,  4616010.40973202,  3946124.94405792,
        2023177.4684687 ,  3975554.48783028,  3624716.9650089 ,
        3210282.74216168,  4668411.38105794,  5893719.66376515,
        6415683.83807236,  4657036.55831934,  2704096.11205266,
        5356909.86181449,  5740682.56798041,  5337586.47961082,
        5444859.96648234,  5702144.57144375,  5865872.30432732,
        3307327.30668416,  6299491.02684292,  7123479.95544321,
        2960326.86653052,  4424323.19483818,  5125081.85591294,
        4947693.93115736,  3629027.81981122,  2975421.52734786,
        3975089.54021919,  8106313.95534003,  5014658.87529549,
        6469749.69804857,  3566139.31348661,  3868652.86219465,
        6344993.74699856,  4482572.73153

In [ ]:
first_row_test_predict=LR.predict([x_test.iloc[0]])

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [ ]:
first_row_test_predict

array([4019080.69890147])

In [ ]:
LR.coef_

array([ 2.53732234e+02,  1.26430216e+05,  1.00306572e+06,  4.31159234e+05,
        4.34983941e+05,  3.95198712e+05,  3.30288607e+05,  1.20896581e+06,
        8.59967238e+05,  2.20086777e+05,  6.93749764e+05, -2.55656836e+05])

In [ ]:
LR.intercept_

360063.04458461143